### ISSUE TITLE
Spread operator

### ISSUE THREAD

**Issue by ghaiklor** [jbach/babel-preset-es2015-node4#4]
Hi. Getting the following error. Strange 'cause seems that spread plugin is required by your preset.

```
/Users/ghaiklor/Library/Projects/kittik/lib/shapes/Rectangle.js:16
    super(...arguments);
          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ghaiklor/Library/Projects/kittik/lib/bin/kittik.js:24:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by jbach** [comment]
Is this still a problem? I cloned your repo and replaced es2015-node5 with es2015-node4, `$ npm run compile` worked without problems?

**Comment by ghaiklor** [comment]
@jbach yes. Running under node 4 and npm 3.
When I've moved to node 5 and preset-node5 it resolves the issue.

**Comment by jbach** [comment]
Spread is available natively in node 5 and is not included by babel-preset-es2015-node5, which is why it works.

This is a babel bug as spreads are correctly transpiled in lib/Shape.js, `create()`. It’s only the `super(...args)` which are not transpiled. Searching through the babel issues shows [this has been an issue before](https://phabricator.babeljs.io/rBC831b420df3ddd27056f4a47022a17107293fc033), but it seems like it is only [fixed](https://github.com/babel/babel/blob/0b88a89b87b18bddecbd9f6eae9eaa993e86bf1e/packages/babel-helper-optimise-call-expression/src/index.js) if you use [transform-es2015-classes or transform-es2015-object-super](https://github.com/babel/babel/search?utf8=%E2%9C%93&q=babel-helper-replace-supers&type=Code).

The bug is that babel-plugin-transform-es2015-spread can’t handle `super(...args)` on it’s own.

**Comment by ghaiklor** [comment]
@jbach I got. Thanks for explanation :+1:

**Comment by jreading** [comment]
so what is this library missing that works with the full preset `babel-preset-es2015`? Seems like it just needs those pieces.

**Comment by yvele** [comment]
@jbach I fixed this issue by adding **transform-es2015-classes** (**transform-es2015-object-super** didn't made it).

So.. why don't we add **transform-es2015-classes** in **es2015-node4**?
